version: '3.4'
services: 
  flower:
    build: .
    image: lovellfleix/flower
    ports:
      - "5555:5555"
    environment:       
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: 'no'
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
